### ISSUE TITLE
get-beats executable

### ISSUE THREAD

**Issue by navanchauhan** [WJLiddy/Macintech#1]
Hey, what is the get-beats file? 

I am trying to run in on macOS but the file has been compiled for GNU/Linux

Can you point me towards its source, so I can compile it?

**Comment by navanchauhan** [comment]
Reverse-engineered the executable, if in an unlikely event someone stumbles upon this issue. I have attached the C code ( rename the file extension to .C )
[test-beattracking.c.txt](https://github.com/WJLiddy/Macintech/files/4307779/test-beattracking.c.txt)

**Comment by WJLiddy** [comment]
glad you were able to fix it, i really like what you've done with your fork!
